name: codal-buildpr

on:
  pull_request:

jobs:
  checkouts:
    runs-on: ubuntu-latest
    container:
      image: nedseb/arm-gcc-none-eabi:latest
      options: --user 1001 --security-opt no-new-privileges
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_PATH: codal/libraries/${{ github.event.repository.name }}
      REPO_URL: ${{ github.event.repository.clone_url }}
    steps:
      - name: checkout codal
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-letssteam
          path: codal

      - name: checkout codal-core
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-core
          path: codal/libraries/codal-core

      - name: checkout codal-stm32-DISCO_L475VG_IOT
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32-DISCO_L475VG_IOT
          path: codal/libraries/codal-stm32-DISCO_L475VG_IOT

      - name: checkout codal-stm32-NUCLEO_F4x1RE
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32-NUCLEO_F4x1RE
          path: codal/libraries/codal-stm32-NUCLEO_F4x1RE
      
      - name: checkout codal-stm32-PNUCLEO_WB55RG
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-stm32-PNUCLEO_WB55RG
          path: codal/libraries/codal-stm32-PNUCLEO_WB55RG

      - name: checkout PR
        uses: actions/checkout@v2
        with:
          path: ${{env.REPO_PATH}}
          submodules: recursive

      - name: create codal.json for codal-stm32-DISCO_L475VG_IOT
        run: |
          echo \
            "{
              \"target\": {
              \"name\": \"$REPO_NAME\", 
              \"url\": \"$REPO_URL\",
              \"branch\": \"main\",
              \"type\": \"git\",
              \"dev\": true
              }
            }" > codal/codal.json
        env:
          REPO_NAME: codal-stm32-DISCO_L475VG_IOT
          REPO_PATH: codal/libraries/codal-stm32-DISCO_L475VG_IOT
          REPO_URL: https://github.com/letssteam/codal-stm32-DISCO_L475VG_IOT
      - name: build codal-stm32-DISCO_L475VG_IOT
        run: |
          cd codal
          ./build.py -c

      - name: clean codal-stm32-DISCO_L475VG_IOT
        run: |
          cd codal
          rm -Rf samples source codal.json 
      - name: create codal.json for codal-stm32-NUCLEO_F4x1RE
        run: |
          echo \
            "{
              \"target\": {
              \"name\": \"$REPO_NAME\", 
              \"url\": \"$REPO_URL\",
              \"branch\": \"main\",
              \"type\": \"git\",
              \"dev\": true
              }
            }" > codal/codal.json
        env:
          REPO_NAME: codal-stm32-NUCLEO_F4x1RE
          REPO_PATH: codal/libraries/codal-stm32-NUCLEO_F4x1RE
          REPO_URL: https://github.com/letssteam/codal-stm32-NUCLEO_F4x1RE
      - name: build codal-stm32-NUCLEO_F4x1RE
        run: |
          cd codal
          ./build.py -c

      - name: clean codal-stm32-NUCLEO_F4x1RE
        run: |
          cd codal
          rm -Rf samples source codal.json 
      
      
      - name: create codal.json for codal-stm32-PNUCLEO_WB55RG
        run: |
          echo \
            "{
              \"target\": {
              \"name\": \"$REPO_NAME\", 
              \"url\": \"$REPO_URL\",
              \"branch\": \"main\",
              \"type\": \"git\",
              \"dev\": true
              }
            }" > codal/codal.json
        env:
          REPO_NAME: codal-stm32-PNUCLEO_WB55RG
          REPO_PATH: codal/libraries/codal-stm32-PNUCLEO_WB55RG
          REPO_URL: https://github.com/letssteam/codal-stm32-PNUCLEO_WB55RG
      - name: build codal-stm32-PNUCLEO_WB55RG
        run: |
          cd codal
          ./build.py -c

      - name: clean codal-stm32-PNUCLEO_WB55RG
        run: |
          cd codal
          rm -Rf samples source codal.json 
